name: Publish
on:
  push: 
    branches:
      - master
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CyanChanges/koishi-publish@main
        name: Publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}


