name: Publish
on:
  push: 
    branches:
      - main
  workflow_dispatch:
    inputs:
      otp-code:
        description: '2FA Authenticate Code'
        required: true
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CyanChanges/koishi-publish@main
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          otp-code: ${{ inputs.otp-code }}


